[package]
name = "DiskSim" # the name of the package
version = "0.1.0"    # the current version, obeying semver
edition = "2021"

[dependencies]
rand = "0.8.4"

[[bin]]
name = "DiskSim"
path = "src/DiskSim.rs"